manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: ubc-rocket
      url-base: https://github.com/UBC-Rocket
    - name: lwgps-remote
      url-base: https://github.com/MaJerle

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v4.3.0
      import: true
    - name: falcon-protos
      remote: ubc-rocket
      revision: main
      path: modules/falcon-protos
    - name: lwgps
      remote: lwgps-remote
      revision: main
      path: modules/lwgps

  self:
    path: app
